source "https://rubygems.org"

#gem "kramdown-parser-gfm"

gem "github-pages", "~> 228", group: :jekyll_plugins

#gem "jekyll", "~> 3.6.2"
#gem "github-pages", group: :jekyll_plugins
#gem "jekyll-remote-theme"

gem "jekyll-include-cache", group: :jekyll_plugins



